pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                
                checkout scm
            }
        }
        stage('Build Stage') {
            steps {
		dir('demo') {
                
                     	sh 'chmod +x mvnw'
			sh './mvnw clean package'
		}
            }
        }
        stage('Archive Artifacts') {
            steps {
                
                archiveArtifacts artifacts: 'demo/target/*.jar', fingerprint: true
            }
        }
    }
}